import Contact from "../models/contact.js";
import HttpError from "../helpers/HttpError.js";


export const getAllContacts = async (_, res, next) => {
  try {
    const contacts = await Contact.find();
    res.json(contacts)
  } catch (error) {
    next(error)
  }
};

export const getOneContact = async (req, res, next) => {
  try {
    const { id } = req.params;
    const contact = await Contact.findById(id);
    if (!contact) {
      throw HttpError(404);
    }
    res.json(contact);
  } catch (error) {
    next(error);
  }
};

export const deleteContact = async (req, res, next) => {
  try {
    const { id } = req.params;
    const contact = await Contact.findByIdAndDelete(id);
    if (!contact) {
      throw HttpError(404);
    }
    res.json(contact);
  } catch (error) {
    next(error);
  }
};

export const createContact = async (req, res) => {
    try {
      const contact = await Contact.create(req.body);
      res.status(201).json(contact)
    } catch (error) {
      next(error)
    }
};

export const updateContact = async (req, res, next) => {
  try {
    const { id } = req.params;
    const contact = await Contact.findByIdAndUpdate(id, req.body, {
      new:true,
    });

    if (!contact) {
      throw HttpError(404);
    }

    res.json(contact);
  } catch (error) {
    next(error);
  }
};

export const updateStatusContact = async (req, res, next) => {
  try {
    console.log(req.params)
    const { id } = req.params;
    const contact = await Contact.findByIdAndUpdate(id, req.body, {
      new: true,
    });
    if(!contact) {
      throw HttpError(404);
    }
    res.json(contact)
  } catch (error) {
    next(error)
  }
}
